version: "3"
services:
  client:
    build: ./client
    ports:
     - 8080:8080
    volumes:
     - ./client:/data

  server:
    build: ./server
    ports:
     - 8081:8081
    volumes:
     - ./server:/data
